### PR TITLE
Feature/auth refactor

### PR DESCRIPTION
**Pull request by jaraco**
* **What kind of change does this PR introduce?**
  - [ ] bug fix
  - [ ] feature
  - [ ] docs update
  - [ ] tests/coverage improvement
  - [X] refactoring
  - [ ] other

* **What is the current behavior?** (You can also link to an open issue here)

`auth_basic` uses deprecated `ntob` and `base64_decode`, causing unnecessary steps of encoding/decoding.

* **What is the new behavior (if this is a feature change)?**

Use the natively-available `bytes` objects directly.

* **Other information**:

* **Checklist**:

  - [X] I think the code is well written
  - [X] I wrote [good commit messages][1]
  - [ ] I have [squashed related commits together][2] after the changes have been approved
  - [X] Unit tests for the changes exist
  - [X] Integration tests for the changes exist (if applicable)
  - [X] I used the same coding conventions as the rest of the project
  - [X] The new code doesn't generate linter offenses
  - [ ] Documentation reflects the changes
  - [X] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences

[1]: http://chris.beams.io/posts/git-commit/
[2]: https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

### CODE REVIEW

**Comment by webknjaz** [comment]
@jaraco I feel like this needs additional unit tests

**Comment by jaraco** [comment]
> I feel like this needs additional unit tests.

I'm unsure for what - this change doesn't introduce or remove functionality. So any tests that were already exercising this functionality are still present. Are you thinking those tests are insufficient to protect from regression around this change? I'm pretty sure when I was implementing these changes, I verified that the code was covered by tests. We certainly don't need tests to capture "basic_auth doesn't call ntob unnecessarily". Are you thinking the private extracted function demands additional unit tests?

**Comment by webknjaz** [comment]
It's just a feeling after I saw an issue created a few days ago, which claims that there's a regression related to auth.

I think that private function could be tested, yes. Because while it's nice and elegant an current point of time, it might catch regression if someone modifies that in future.

**Comment by jaraco** [comment]
I've several times now started writing tests for this change, but I've run into a couple of roadblocks. The first was that neither test_auth_basic nor auth_basic support unicode literals, which makes it harder to write robust tests, so I set out to create new module. I even started creating a new test suite just to test this function.

But then as I started writing tests, I realized that these tests are enforcing implementation details - internal interfaces that should be free to change.

I'm now convinced this change doesn't need a test unless the tests for the plugin itself need to be enhanced to improve coverage, but that's outside of the scope for this change, so I'm going to proceed with it as-is.

Thanks for the review in any case.

**Pull request merged**
