### PR TITLE
Deprecate old auth tools

### PR DESCRIPTION
**Pull request by jaraco**
This change is the first of two phases for #1688.

### CODE REVIEW

**Review by webknjaz — CHANGES_REQUESTED** [review]
Plz don't remove tests as this will conflict with #1683. We need to move tests to valid implementation.

**Comment by jaraco** [comment]
> conflict with #1683

Perhaps #1683 should disregard the deprecated modules?

> We need to move tests to valid implementation.

Is that true? Or can we simply ignore them? If someone wishes to port/implement those tests for the new, preferred tools, I welcome that, but I'd consider that outside the scope of this effort.

**Comment by webknjaz** [comment]
This pull request fixes 1 alert - [view on lgtm.com](https://lgtm.com/projects/g/cherrypy/cherrypy/rev/pr-09499e69661ded5f51b4edc04f2d73c5d8c29f80)

**fixed alerts:**

* 1 for Potentially uninitialized local variable

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by jaraco** [comment]
I've removed the commit that removed the tests.

**Comment by webknjaz** [comment]
Actually, there's `DeprecationTool` in _cptools. And it looks like a right place for adding deprecation

**Comment by jaraco** [comment]
Hmm. I honestly don't understand how DeprecatedTool is meant to work. In the two places it's used, it's not wrapping another tool, but merely acting as a stand-in for another tool that was removed. I think we should remove the DeprecatedTool also, because its name betrays its purpose (it's not deprecating if it's replacing) and because there's no useful example of using it to deprecate a tool.

**Pull request merged**
