### PR TITLE
Drop support for Python 3.3.

### LINKED ISSUE #1666: Drop support for Python 3.3
The [tests on failing on Python 3.3](https://travis-ci.org/cherrypy/cherrypy/jobs/310860577) due to pytest-dev/pytest#2966, blocking releases.

### PR DESCRIPTION
**Pull request by jaraco**
Fixes #1666.

### CODE REVIEW

**Review by webknjaz — APPROVED** [review]

**Comment by jaraco** [comment]
Test is failing with

```
――――――――――――――――――――――――― ToolTests.testCombinedTools ――――――――――――――――――――――――――

self = <cherrypy.test.test_tools.ToolTests testMethod=testCombinedTools>

    def testCombinedTools(self):

        expectedResult = (ntou('Hello,world') +

                          europoundUnicode).encode('utf-8')

        zbuf = io.BytesIO()

        zfile = gzip.GzipFile(mode='wb', fileobj=zbuf, compresslevel=9)

        zfile.write(expectedResult)

        zfile.close()

    

        self.getPage('/euro',

                     headers=[

                         ('Accept-Encoding', 'gzip'),

                         ('Accept-Charset', 'ISO-8859-1,utf-8;q=0.7,*;q=0.7')])

        self.assertInBody(zbuf.getvalue()[:3])

    

        zbuf = io.BytesIO()

        zfile = gzip.GzipFile(mode='wb', fileobj=zbuf, compresslevel=6)

        zfile.write(expectedResult)

        zfile.close()

    

        self.getPage('/decorated_euro', headers=[('Accept-Encoding', 'gzip')])

        self.assertInBody(zbuf.getvalue()[:3])

    

        # This returns a different value because gzip's priority was

        # lowered in conf, allowing the rotator to run after gzip.

        # Of course, we don't want breakage in production apps,

        # but it proves the priority was changed.

        self.getPage('/decorated_euro/subpath',

                     headers=[('Accept-Encoding', 'gzip')])

        if six.PY3:

>           self.assertInBody(bytes([(x + 3) % 256 for x in zbuf.getvalue()]))

cherrypy/test/test_tools.py:381: 

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

.tox/cheroot-master/lib/python3.6/site-packages/cheroot/test/webtest.py:454: in assertInBody

    self._handlewebError(msg)

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <cherrypy.test.test_tools.ToolTests testMethod=testCombinedTools>

msg = 'b\'"\\x8e\\x0b\\x03!\\x95(]\\x05\\x02\\xf6K\\xd0\\xcc\\xcc\\xda,\\xd22\\xcdL<\\xd7sk4\\x03\\xe62\\x9e\\x8e\\x12\\x03\...\x0b\\x03"\\x95(]\\x05\\x02\\xf6K\\xd0\\xcc\\xcc\\xda,\\xd22\\xcdL<\\xd7sk4\\x03\\xe62\\x9e\\x8e\\x12\\x03\\x03\\x03\''

    def _handlewebError(self, msg):

        print('')

        print('    ERROR: %s' % msg)

    

        if not self.interactive:

>           raise self.failureException(msg)

E           AssertionError: b'"\x8e\x0b\x03!\x95(]\x05\x02\xf6K\xd0\xcc\xcc\xda,\xd22\xcdL<\xd7sk4\x03\xe62\x9e\x8e\x12\x03\x03\x03' not in body: b'"\x8e\x0b\x03"\x95(]\x05\x02\xf6K\xd0\xcc\xcc\xda,\xd22\xcdL<\xd7sk4\x03\xe62\x9e\x8e\x12\x03\x03\x03'

.tox/cheroot-master/lib/python3.6/site-packages/cheroot/test/webtest.py:310: AssertionError
```

That seems like it must be unrelated to the PR, so I'll restart it and see if it's just intermittent.

**Comment by jaraco** [comment]
Test passed subsequently.

**Comment by jaraco** [comment]
released as 13.0.0.

**Comment by webknjaz** [comment]
@jaraco this test you mentioned in https://github.com/cherrypy/cherrypy/pull/1668#issuecomment-349060151 is still flakily failing sometimes:

```python-traceback
E           AssertionError: b'"\x8e\x0b\x03\x85\x07*^\x05\x02\xf6K\xd0\xcc\xcc\xda,\xd22\xcdL<\xd7sk4\x03\xe62\x9e\x8e\x12\x03\x03\x03' not in body: b'"\x8e\x0b\x03\x86\x07*^\x05\x02\xf6K\xd0\xcc\xcc\xda,\xd22\xcdL<\xd7sk4\x03\xe62\x9e\x8e\x12\x03\x03\x03'
```

It differs in only one (4th) byte: `\x85` vs. `\x86`. In your example fourth byte is also different (`!` != `"`).

**Pull request merged**
