### PR TITLE
Try to do the right thing when autoreloading a process invoked with 'python -m'

### LINKED ISSUE #1411: Autoreload can't handle module / __main__
Originally reported by: **Anonymous**

----------------------------------------

I try to run `python -m mymodule` (and `mymodule/` contains `__main__.py`). The module then spawns a CherryPy server. Everything works until it tries to reload itself, where it tries to run `/path/to/python mymodule/__main__.py`, without importing `mymodule`. This makes my module to throw various `ImportError`s that claim `mymodule` cannot be found.

Could you share any tips how to organize the code, or change the way I run the server, to make reloading work?

----------------------------------------
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1411

### PR DESCRIPTION
**Pull request by batterseapower**
Appears to fix #1411

### CODE REVIEW

**Comment by jaraco** [comment]
Excellent - thanks!

**Comment by saioia** [comment]
Thanks a lot! This will really help my workflow.

**Comment by sevmonster** [comment]
While it does recognize the right files to reload now, I still think local imports are messing up -- I will investigate later this week.

**Comment by sevmonster** [comment]
Forgot to post back, I messed with it but was unable to find the source of the issue... Local imports kinda work? Sometimes they load correctly and sometimes they don't. It's a little out of my expertise, import system has always confounded me.

**Pull request merged**
