### PR TITLE
WIP: Use "surrogateescape" to decode invalid URL.

### PR DESCRIPTION
**Pull request by ikus060**
See ticket #1485

### CODE REVIEW

**Comment by jaraco** [comment]
Thanks! The test case looks great. And I think the fix is on the right track, but as you observed, it causes other parts of the test suite to fail.

Additionally, I think we should drop the "Just pass them through and hope". If there's a UnicodeEncodeError, then the application is violating the WSGI spec and an error should be raised. And with the surrogate escape, the UnicodeDecodeError should never happen.

I'm going to accept this PR but move it into another branch so we can iterate on it.

**Comment by jaraco** [comment]
I've moved that commit into the `stricter-url-handling` branch.

**Comment by ikus060** [comment]
Will it someday be part of master branches ? Whats is your plan about "stricter-url-handling" ?

**Comment by jaraco** [comment]
Before it can go into master, the tests have to pass.

I started looking at `test_objectmapping.ObjectMappingTest.testObjectMapping`, but it's a mess. If I use a UTF-8 encoded URL for that test, the test start passing on Python 3 and failing on Python 2. The ISO-8859-1 encoded URL is actually wrong, but it probably works because of the generous ISO-8859-1 decoding in `ntob` and `ntou`.

The encode/decode behavior in `AppResponse.run` only applies to Python 3, which seems wrong. It should probably apply to Python 2 and 3, but if I enable it for Python 2, it breaks a lot of things. This is going to be a tough nut to crack, and will probably require a fairly massive overhaul of the Unicode handling in CherryPy.

It's conceivable we could just disable the failing tests and kick this can down the road, causing disruption in the codebase and in our user's apps. It's also conceivable we could just drop support for Python 2.

I'd rather, however, just iterate on this branch and work toward a solution with proper passing tests.

**Pull request merged**
