### PR TITLE
docs: Fix link to wikipedia

### PR DESCRIPTION
**Pull request by bersace**
**What kind of change does this PR introduce?**
  - [ ] bug fix
  - [ ] feature
  - [x] docs update
  - [ ] tests/coverage improvement
  - [ ] refactoring
  - [ ] other

**Checklist**:

  - [ ] I think the code is well written
  - [x] I wrote [good commit messages][1]
  - [ ] I have [squashed related commits together][2] after the changes have been approved
  - [ ] Unit tests for the changes exist
  - [ ] Integration tests for the changes exist (if applicable)
  - [ ] I used the same coding conventions as the rest of the project
  - [ ] The new code doesn't generate linter offenses
  - [ ] Documentation reflects the changes
  - [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences

[1]: http://chris.beams.io/posts/git-commit/
[2]: https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

### CODE REVIEW

**Comment by bersace** [comment]
I have reflowed the entire paragraph.

**Comment by webknjaz** [comment]
Why do you think longer lines are better?

**Comment by webknjaz** [comment]
Anyway, thanks for your contribution!

**Comment by bersace** [comment]
@webknjaz hmm, sorry, i just reflowed thinking some editorconfig file will tell what's right. I didn't even notice the difference.

**Comment by webknjaz** [comment]
It just that it breaks `git blame` making it harder to get to the original author if needed. That's why I prefer to avoid unnecessary changes :)

**Comment by bersace** [comment]
@webknjaz i agree it was unnecessary. It's my mistake. I thought that line was too longth due to `https://`, but that's my mistake. Sorry for the blame :/

**Comment by webknjaz** [comment]
No worries, we can live with it :)

**Pull request merged**
