### PR TITLE
HTTPError provides context manager for handling exceptions.

### PR DESCRIPTION
**Pull request by coady**
Implementation for #1473.
- [x] tests
- [x] implementation
- [x] docs

### CODE REVIEW

**Comment by webknjaz** [comment]
Could you please upgrade this PR in accordance to [@jaraco's suggestions](/cherrypy/cherrypy/issues/1473#issuecomment-241396807)?

**Comment by webknjaz** [comment]
@coady ping

**Comment by coady** [comment]
Added docs, and examples in `cherrypy.lib`, just to demonstrate how common the pattern is.

**Comment by webknjaz** [comment]
And what about `trap` and other stuff?

**Comment by jaraco** [comment]
@webknjaz What would you like to see for this to be acceptable?

**Comment by webknjaz** [comment]
I'd like to see your suggestions with trap decorator and non-error response handler: https://github.com/cherrypy/cherrypy/issues/1473#issuecomment-241396807. But they could be implemented in separate PR.

**Comment by jaraco** [comment]
That sounds like a good plan to me.

**Pull request merged**
