### PR TITLE
Re-spawn app with the original interpreter args

### LINKED ISSUE #1500: Cherrypy does not pass -O parameter on AutoReload
Hi guys,

i just noticed that if i start the engine with python -O myStarter.py and cherrypy reloaded via its autoreload functionality, it starts without -O again. Really annoying because i use different configurations on release system

### PR DESCRIPTION
**Pull request by webknjaz**
Fix #1500
@jaraco, @cinatic plz take a look

### CODE REVIEW

**Comment by cinatic** [comment]
thanks for you effort:

i get an wierd error on autoreload:
/usr/bin/python: can't open file 'python': [Errno 2] No such file or directory

```bash
[cin@localhost uniq2]$ ll /usr/bin/python
925954 lrwxrwxrwx 1 root root 7 Jun 28 09:03 /usr/bin/python -> python3
```

**Comment by cinatic** [comment]
sorry forgot to remove line with args.insert(0, sys.executable). 

works great for me. thank you very much

**Comment by webknjaz** [comment]
@jaraco do you have any objections against merging this?

**Comment by jaraco** [comment]
No objections.

**Comment by Safihre** [comment]
I am getting an error, Windows 10, Python 2.7.12:

```
Traceback (most recent call last):
  File "C:\Users\x\Documents\GitHub\sabnzbd\cherrypy\process\wspbus.py", line 380, in _do_execv
    args = self._get_true_argv()
  File "C:\Users\x\Documents\GitHub\sabnzbd\cherrypy\process\wspbus.py", line 413, in _get_true_argv
    ctypes.pythonapi.Py_GetArgcArgv(ctypes.byref(argc), ctypes.byref(argv))
  File "C:\Python27\lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'Py_GetArgcArgv' not found
```

**Comment by webknjaz** [comment]
@Safihre I've created issue #1506 to discuss and investigate this. If anything comes to your mind, just post it there.

**Pull request merged**
